### ISSUE TITLE
update project settings

### ISSUE THREAD

**Issue by machadev** [tattn/NFCReader#2]
Please update project settings.
1.MultipleTags.swift, Service.swift is not found.
Because there was renamed.
2.Reader.swift was failed to build.(Swift 5.0)
DispatchQueue.mainAsyncIfNeeded -> DispatchQueue.main.async
(XCode 11.0, Swift 5.0)

I was fixed there settings and I can read Felica card.

**Comment by tattn** [comment]
Thanks for this issue!
I fixed https://github.com/tattn/NFCReader/pull/3

Please reopen it if you still have some errors.
